### ISSUE TITLE
Gate opens the wrong way

### ISSUE THREAD

**Issue by Griffone** [Hrenli/MGConstruction#2]
The moded gate opens towards the player, where as vanilla gates open away from player.

**Comment by Hrenli** [comment]
That's because mod artist draw them wrong way. Fixed (by rotating the models 180 degrees in blockstates.json).

**Comment by Yorla** [comment]
Я могу переделать модель.

On 20 Jan 2016 10:54, "Hrenli" <notifications@github.com> wrote:
>
> That's because mod artist draw them wrong way. Fixed (by rotating the
models 180 degrees in blockstates.json).
